"""The modifier vocabulary. Every effect in the game names one of these keys.

This file exists so that a typo cannot become a silent no-op. Chrome, programs,
deck components, origins, and situational modifiers all express themselves as
`{key: number}` dicts, and `validate.py` rejects any key not declared here.
Without that, `{'noize_mult': 0.8}` is a piece of cyberware that does nothing,
ships, and is never noticed because nobody can feel a 20% noise reduction.

Two kinds of key, distinguished by how they combine:

- **Additive** keys sum. Attribute and skill bonuses, flat capacity.
- **Multiplicative** keys multiply, and default to 1.0. Anything shaped like a
  rate or a scale factor.

Combining a multiplicative key additively is the classic way a stacking bug
turns into a build that trivialises the game, so the split is enforced rather
than documented.
"""

from __future__ import annotations

from .attributes import ATTR_KEYS
from .skills import SKILL_KEYS

#: key -> one-line description, shown by `char --effects` and in item detail.
ADDITIVE: dict[str, str] = {
    # attributes
    **{k: f'{k.title()} attribute' for k in ATTR_KEYS},
    # derived
    'bandwidth': 'Cyberware capacity',
    'integrity': 'Damage absorbed before the connection drops',
    'focus': 'Precision actions per run',
    'tempo': 'Free actions banked as you work (2: one in three, 3: one in two)',
    'memory': 'Deck memory for programs',
    'heat_cap': 'Thermal headroom before components take damage',
    'ice_damage': 'Damage dealt to countermeasures',
    'crack_bonus': 'Bonus to service intrusion checks',
    'crypto_bonus': 'Bonus to cryptography checks',
    'pretext_bonus': 'Bonus to social engineering checks',
    'evade_bonus': 'Bonus to slipping a lock-on when a hunter lunges',
    'composure': 'Resistance to black ICE and panic',
    'armour': 'Street damage absorbed from each hit in a fight',
    'strike_bonus': 'Bonus to landing a strike in a fight',
    'strike_damage': 'Damage added to a landed strike',
    'guard_bonus': 'Bonus to covering up in a fight',
    'cover': 'How fast the story a faction is assembling about you falls apart',
    'tell_lead': 'Ticks of advance warning on an ICE tell',
    'legwork_bonus': 'Quality of information bought before a run',
    'scan_depth': 'How far a scan sees from the node you stand on',
    # skills, as `skill_<key>`
    **{f'skill_{k}': f'{k.title()} skill' for k in SKILL_KEYS},
}

#: key -> one-line description. All default to 1.0 and multiply together.
MULTIPLICATIVE: dict[str, str] = {
    'noise_mult': 'Noise generated by your actions',
    'trace_mult': 'Rate the trace advances',
    'residue_mult': 'Evidence left behind',
    'heat_mult': 'Faction heat accrued from residue',
    'tick_mult': 'Time each action costs',
    'price_mult': 'What merchants charge you',
    'pay_mult': 'What contracts pay you',
    'rep_mult': 'Reputation gained from completed work',
    'repair_mult': 'Cost to repair deck components',
    'ice_dr': 'Damage taken from countermeasures',
}

ALL: dict[str, str] = {**ADDITIVE, **MULTIPLICATIVE}

#: Which way is up, for every multiplicative key. Additive keys never need
#: this: more of an attribute is more of an attribute. Rates are the opposite
#: half the time, and nothing else in the codebase knew it, so anything
#: printing a modifier in colour had to guess and would eventually guess that
#: doubling the trace rate was good news.
#:
#: Declared exhaustively rather than as a set of exceptions, and `validate.py`
#: checks it covers exactly `MULTIPLICATIVE`, so a new rate cannot be added
#: without somebody deciding which direction it points.
DIRECTION: dict[str, str] = {
    'noise_mult': 'down',
    'trace_mult': 'down',
    'residue_mult': 'down',
    'heat_mult': 'down',
    'tick_mult': 'down',
    'price_mult': 'down',
    'repair_mult': 'down',
    'ice_dr': 'down',
    'pay_mult': 'up',
    'rep_mult': 'up',
}

LOWER_IS_BETTER: frozenset[str] = frozenset(
    k for k, way in DIRECTION.items() if way == 'down')


def improves(key: str, value: float) -> bool:
    """Whether this modifier is good news for the character carrying it."""
    if key in MULTIPLICATIVE:
        return value < 1.0 if key in LOWER_IS_BETTER else value > 1.0
    return value > 0


def check(effects: dict, where: str) -> list[str]:
    """Validate an effects dict. Returns a list of problems, empty if clean."""
    problems: list[str] = []
    for key, value in effects.items():
        if key not in ALL:
            problems.append(f'{where}: unknown effect key {key!r}')
            continue
        if not isinstance(value, (int, float)) or isinstance(value, bool):
            problems.append(f'{where}: {key} is {value!r}, expected a number')
            continue
        if key in MULTIPLICATIVE and value <= 0:
            problems.append(
                f'{where}: {key} is {value}, but multiplicative effects must be '
                f'positive (1.0 is no change)')
    return problems


def merge(*dicts: dict) -> dict:
    """Combine effect dicts under the right rule for each key."""
    out: dict[str, float] = {}
    for d in dicts:
        for k, v in (d or {}).items():
            if k in MULTIPLICATIVE:
                out[k] = out.get(k, 1.0) * v
            else:
                out[k] = out.get(k, 0) + v
    return out


def describe(key: str, value: float) -> str:
    """One modifier as a line of player-facing text."""
    label = ALL.get(key, key)
    if key in MULTIPLICATIVE:
        pct = (value - 1.0) * 100
        if abs(pct) < 0.5:
            return f'{label}: no change'
        sign = '+' if pct > 0 else ''
        return f'{label}: {sign}{pct:.0f}%'
    sign = '+' if value > 0 else ''
    return f'{label}: {sign}{value:g}'
